# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'texture_synthesis.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 515))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.insert = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert.sizePolicy().hasHeightForWidth())
        self.insert.setSizePolicy(sizePolicy)
        self.insert.setObjectName("insert")
        self.gridLayout.addWidget(self.insert, 0, 0, 1, 2)
        self.input_path = QtWidgets.QTextBrowser(self.centralwidget)
        self.input_path.setMaximumSize(QtCore.QSize(16777215, 20))
        self.input_path.setReadOnly(True)
        self.input_path.setObjectName("input_path")
        self.gridLayout.addWidget(self.input_path, 0, 2, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(131, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(201, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 8, 1, 1)
        self.output = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output.sizePolicy().hasHeightForWidth())
        self.output.setSizePolicy(sizePolicy)
        self.output.setObjectName("output")
        self.gridLayout.addWidget(self.output, 1, 0, 1, 2)
        self.output_path = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_path.setMaximumSize(QtCore.QSize(16777215, 20))
        self.output_path.setObjectName("output_path")
        self.gridLayout.addWidget(self.output_path, 1, 2, 1, 3)
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setMinimumSize(QtCore.QSize(600, 400))
        self.result.setMaximumSize(QtCore.QSize(600, 400))
        self.result.setAutoFillBackground(True)
        self.result.setText("")
        self.result.setScaledContents(True)
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 1, 6, 10, 3)
        self.sample = QtWidgets.QLabel(self.centralwidget)
        self.sample.setMinimumSize(QtCore.QSize(300, 200))
        self.sample.setMaximumSize(QtCore.QSize(300, 200))
        self.sample.setAutoFillBackground(True)
        self.sample.setText("")
        self.sample.setScaledContents(True)
        self.sample.setObjectName("sample")
        self.gridLayout.addWidget(self.sample, 2, 0, 1, 5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 2)
        self.label_result_size = QtWidgets.QLabel(self.centralwidget)
        self.label_result_size.setObjectName("label_result_size")
        self.gridLayout.addWidget(self.label_result_size, 4, 0, 1, 2)
        self.label_width = QtWidgets.QLabel(self.centralwidget)
        self.label_width.setObjectName("label_width")
        self.gridLayout.addWidget(self.label_width, 5, 1, 1, 1)
        self.input_width = QtWidgets.QLineEdit(self.centralwidget)
        self.input_width.setMaximumSize(QtCore.QSize(50, 16777215))
        self.input_width.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_width.setClearButtonEnabled(False)
        self.input_width.setObjectName("input_width")
        self.gridLayout.addWidget(self.input_width, 5, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(131, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 4, 2, 1)
        self.label_hight = QtWidgets.QLabel(self.centralwidget)
        self.label_hight.setObjectName("label_hight")
        self.gridLayout.addWidget(self.label_hight, 6, 1, 1, 1)
        self.input_hight = QtWidgets.QLineEdit(self.centralwidget)
        self.input_hight.setMaximumSize(QtCore.QSize(50, 16777215))
        self.input_hight.setObjectName("input_hight")
        self.gridLayout.addWidget(self.input_hight, 6, 3, 1, 1)
        self.label_method = QtWidgets.QLabel(self.centralwidget)
        self.label_method.setObjectName("label_method")
        self.gridLayout.addWidget(self.label_method, 7, 0, 1, 1)
        self.input_method = QtWidgets.QComboBox(self.centralwidget)
        self.input_method.setObjectName("input_method")
        self.input_method.addItem("")
        self.input_method.addItem("")
        self.gridLayout.addWidget(self.input_method, 7, 1, 1, 3)
        self.label_kernel = QtWidgets.QLabel(self.centralwidget)
        self.label_kernel.setScaledContents(False)
        self.label_kernel.setObjectName("label_kernel")
        self.gridLayout.addWidget(self.label_kernel, 8, 1, 1, 2)
        self.input_kernel = QtWidgets.QLineEdit(self.centralwidget)
        self.input_kernel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.input_kernel.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_kernel.setObjectName("input_kernel")
        self.gridLayout.addWidget(self.input_kernel, 8, 3, 1, 1)
        self.label_tolerance = QtWidgets.QLabel(self.centralwidget)
        self.label_tolerance.setScaledContents(False)
        self.label_tolerance.setObjectName("label_tolerance")
        self.gridLayout.addWidget(self.label_tolerance, 9, 1, 1, 1)
        self.input_tolerance = QtWidgets.QLineEdit(self.centralwidget)
        self.input_tolerance.setMaximumSize(QtCore.QSize(50, 16777215))
        self.input_tolerance.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_tolerance.setObjectName("input_tolerance")
        self.gridLayout.addWidget(self.input_tolerance, 9, 3, 1, 1)
        self.label_overlap = QtWidgets.QLabel(self.centralwidget)
        self.label_overlap.setEnabled(True)
        self.label_overlap.setObjectName("label_overlap")
        self.gridLayout.addWidget(self.label_overlap, 10, 1, 1, 1)
        self.input_overlap = QtWidgets.QLineEdit(self.centralwidget)
        self.input_overlap.setMaximumSize(QtCore.QSize(50, 16777215))
        self.input_overlap.setObjectName("input_overlap")
        self.gridLayout.addWidget(self.input_overlap, 10, 3, 1, 1)
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.generate.setFont(font)
        self.generate.setObjectName("generate")
        self.gridLayout.addWidget(self.generate, 11, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionsettings = QtWidgets.QAction(MainWindow)
        self.actionsettings.setObjectName("actionsettings")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.insert.setStatusTip(_translate("MainWindow", "no spaces in path!"))
        self.insert.setText(_translate("MainWindow", "Insert Sample"))
        self.input_path.setStatusTip(_translate("MainWindow", "no spaces in path!"))
        self.output.setStatusTip(_translate("MainWindow", "no spaces in path!"))
        self.output.setText(_translate("MainWindow", "Output Location"))
        self.output_path.setStatusTip(_translate("MainWindow", "no spaces in path!"))
        self.label_result_size.setText(_translate("MainWindow", "Result Size"))
        self.label_width.setText(_translate("MainWindow", "Width:"))
        self.input_width.setStatusTip(_translate("MainWindow", "width of the result image in pixels"))
        self.label_hight.setText(_translate("MainWindow", "Hight:"))
        self.input_hight.setStatusTip(_translate("MainWindow", "hight of the result image in pixels"))
        self.label_method.setText(_translate("MainWindow", "method:"))
        self.input_method.setItemText(0, _translate("MainWindow", "Image Quilting"))
        self.input_method.setItemText(1, _translate("MainWindow", "Non-parametric Sampling"))
        self.label_kernel.setText(_translate("MainWindow", "Kernel/Block Size:"))
        self.input_kernel.setStatusTip(_translate("MainWindow", "image quilting requires block size. non_parametric sampling requiers odd number kernel size (pixels)"))
        self.label_tolerance.setText(_translate("MainWindow", "Tolerance:"))
        self.input_tolerance.setStatusTip(_translate("MainWindow", "rms tolerance (0-1)"))
        self.label_overlap.setText(_translate("MainWindow", "overlap:"))
        self.input_overlap.setStatusTip(_translate("MainWindow", "block overlap for image quilting (0-1)"))
        self.generate.setStatusTip(_translate("MainWindow", "create "))
        self.generate.setText(_translate("MainWindow", "Generate Texture"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionsave_as.setText(_translate("MainWindow", "save as"))
        self.actionsettings.setText(_translate("MainWindow", "settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
